version: "3"

services:
  mongodb-backup:
    build: .
    image: macyan13/mongodb-backup:latest
    container_name: "mongodb-backup"
    restart: always
    environment:
      - MONGO_HOST
      - MONGO_PORT
      - MONGO_USERNAME
      - MONGO_PASSWD
      - MONGO_DB
      - MONGO_BACKUP_CRON_TIME=*/5 * * * *
      - MONGO_BACKUP_MAX_BACKUPS=10
      - INIT_BACKUP=true
    volumes:
      - ./backup:/backup

#  mongo:
#    image: mongo:4.2.3
#    restart: always
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
#      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWD}
